# secrets required:
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN

name: Build and push Server Crawler image
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push update image
        uses: docker/build-push-action@v6
        with:
          file: ./ServerCrawler/Dockerfile
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/servercrawler:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
