# secrets required:
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
# SETTINGS_FILE
# PAT
name: Run Docker build of Village Crawler
on:
  workflow_dispatch:
  schedule:
  # from RELEASE POLARBEAR 1171.1, map.sql is updated every midnight server time
  # (which is 00:00 GMT+1 or 23:00 GMT)
  # we execute after 1 hour to make sure map.sql updated
    - cron:  00 00 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Download setting file
        run: |
          curl -s -H "Authorization: token ${{ secrets.PAT }} " ${{ secrets.SETTINGS_FILE }}/appsettings.Production.json -H "Accept: application/vnd.github.raw" > appsettings.Production.json
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run
        run: |
          docker run --rm -v ./appsettings.Production.json:/app/appsettings.Production.json ${{ secrets.DOCKERHUB_USERNAME }}/villagecrawler:latest 

     
